# Use a minimal Golang Alpine image as the base image
FROM golang:1.16-alpine AS builder

RUN apk update && apk add --no-cache git
RUN apk add --no-cache bash

COPY . /go/src/app

# Set the working directory within the container
WORKDIR /go/src/app/cmd/tester

RUN go get -d -v

# Build the Go application with static linking and stripped symbols
RUN go build -o tester -ldflags="-s -w" main.go

# Specify the command to run when the container starts
CMD ["./tester/tester"]